SCHOOLS = [
  'Choose a School'
  'Anna Brochhausen School 88',
  'Arlington Woods School 99',
  'Arsenal Technical High School',
  'Broad Ripple Magnet High School for the Arts and Humanities',
  'Brookside School 54',
  'IPS Career Technology Center',
  'Carl Wilde School 79',
  'Center for Inquiry School 2',
  'Center for Inquiry School 27',
  'Center for Inquiry School 84',
  'Charles Warren Fairbanks School 105',
  'Christian Park School 82',
  'Clarence Farrington School 61',
  'Cold Spring School',
  'Crispus Attucks Medical Magnet High School',
  'Daniel Webster School 46',
  'Elder W. Diggs School 42',
  'Eleanor Skillen School 34',
  'Eliza A. Blaker School 55',
  'Ernie Pyle School 90',
  'Floro Torrence School 83',
  'Francis Bellamy School 102',
  'Francis Scott Key School 103',
  'Francis W. Parker School 56',
  'Gambold Preparatory Magnet High School',
  'George S. Buck School 94',
  'George H. Fisher School 93',
  'George W. Julian School 57',
  'George Washington Carver School 87',
  'George Washington Community High School',
  'Harshman Magnet Middle School',
  'IPS/Butler University Laboratory School 60',
  'James A. Garfield School 31',
  'James Russell Lowell School 51',
  'James Whitcomb Riley School 43',
  'John Marshall Community High School',
  'Jonathan Jennings School 109',
  'Joyce Kilmer Academy 69',
  'Key Learning Community',
  'Lew Wallace School 107',
  'Louis B. Russell Jr. School 48',
  'Meredith Nicholson School 96',
  'Nicholson Performing Arts Academy at School 70',
  'Northwest Community High School',
  'Paul I. Miller School 114',
  'Ralph Waldo Emerson School 58',
  'Raymond F. Brandes School 65',
  'Riverside School 44',
  'Robert Lee Frost School 106',
  'Rousseau McClellan School 91',
  'Shortridge Magnet High School for Law and Public Policy',
  'Sidener Academy for High Ability Students',
  'Stephen Foster School 67',
  'SUPER School 19',
  'Theodore Potter School 74',
  'Thomas D. Gregg School 15',
  'Washington Irving School 14',
  'Wendell Phillips School 63',
  'William McKinley School 39',
  'William Penn School 49'
]

PROGRAMS = [
  'Choose a Program'
  'Red',
  'Orange',
  'Yellow',
  'Green',
  'Blue',
  'Indigo',
  'Violet'
]
